version: '3.7'

services:
  app:
    image: covid-backend:latest
    environment: 
      FLASK_APP: application
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: "postgres://covid:covid@postgres:5432/covid"
      BASIC_AUTH_USERNAME: covid
      BASIC_AUTH_PASSWORD: covid
    ports:
      - "8080:80"
    networks: 
      - postgres

  postgres:
    image: postgres:10.7
    environment:
      POSTGRES_USER: covid
      POSTGRES_PASSWORD: covid
      POSTGRES_DB: covid
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: covid
      PGADMIN_DEFAULT_EMAIL: covid
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5433:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
    postgres:
    pgadmin: