FROM python:3.7-slim

# TODO: apt update, etc, install packages

ENV USER="app"
ENV WORKDIR="/app"

# Set up workdir
RUN useradd -ms /bin/bash ${USER} && mkdir ${WORKDIR} && chown -R ${USER}:${USER} ${WORKDIR}

USER ${USER}
WORKDIR ${WORKDIR}

